### ISSUE TITLE
Listen to events/functions inside state

### ISSUE THREAD

**Issue by danielcharrua** [LennartHennigs/SimpleFSM#15]
Hello, I'm trying to understand the docs and use this machine on a project. The project has different screens (states) and two buttons, the user can use buttons to do different things inside each screen. Sometimes the button only switch screens (state) but others I need to update some value each time the button is pressed inside that particular state.

I didn't find any examples with this type of logic or maybe I can't fully understand it.

Any ideas on what would be the best way to achieve this? Having different functions per state, that run (or listen) to buttons or external events (like websockets) while the state is activated?

I think I'm looking to have like different loops by state (kind of).

Let me know your thoughts, thank you.

**Comment by LennartHennigs** [comment]
Say you describe a menu system. Some entries lead to changes in the existing screen, one loads another screen.
Each entry in the menu system needs to be a state. One button transitions through the states and highlights the state.
The other selects an entry and thus has different events for inline changes, or for loading a new screen when the state is set for this.
