### ISSUE TITLE
Typo in changelog entry for release 1.3.1

### ISSUE THREAD

**Issue by mdxs** [LennartHennigs/SimpleFSM#21]
It appears there is a typo in the changelog entry for release 1.3.1:
https://github.com/LennartHennigs/SimpleFSM/blob/f06574716daf6b1fedc2d18c8fe35c7b630fd64f/CHANGELOG.md?plain=1#L9

The day of the date is wrong... but the year should also be 2024?

So this probably should be changed to:
```
## 1.3.1 - 2024-10-27
```

As that is the `Blame` date.

**Comment by LennartHennigs** [comment]
Thx for pointing it out. Changed it.
