### ISSUE TITLE
Compile error with Button2::CallbackFunction

### ISSUE THREAD

**Issue by tkleiner** [LennartHennigs/SimpleFSM#4]
Nice little library! 

Today I started with the `MixedTransitions.ino` example and ran into the following compile error. 
```
Cannot initialize a parameter of type 'Button2::CallbackFunction' (aka 'void (*)(Button2 &)') with an lvalue of type 'void (Button2)': type mismatch at 1st parameter ('Button2 &' vs 'Button2')
```
The problem is in this line:
https://github.com/LennartHennigs/SimpleFSM/blob/a75124579350a553cec431d1bc977f060928ce40/examples/MixedTransitions/MixedTransitions.ino#L69

I have looked into the examples from Button2, e.g. [SingleButton.ino](https://github.com/LennartHennigs/Button2/blob/master/examples/SingleButton/SingleButton.ino), and I think this line should be
```
void button_handler(Button2& btn) {
```

The same issue is in [SimpleTransitionWithButton.ino](https://github.com/LennartHennigs/SimpleFSM/blob/master/examples/SimpleTransitionWithButton/SimpleTransitionWithButton.ino#L71)

Thank you.

**Comment by LennartHennigs** [comment]
Hey,
thanks for reaching out. 
Updated both examples! Thanks.

Cheers
l.
