### ISSUE TITLE
TimedTransition fires immediately.

### ISSUE THREAD

**Issue by Roelli** [LennartHennigs/SimpleFSM#5]
I don't know if intended or not. 
I would except that a TimedTransition only transitions the StateMachine if the time was spend entirely in given state. 
The current implementation of the run Loop doesn't reset the start times of the transitions of the current state. This can lead to some effects where the timed transition fires immediately after the state is entered. 

See MixedTransitions Example where red changes directly to green again after the button was pressed and the light turns back to red.

**Comment by bloodhoundmichael** [comment]
I have the following test:
```cpp
#include <Arduino.h>
#include <unity.h>
#include <SimpleFSM.h>

void setUp() {}
void tearDown() {}

void test_mixed_transition_toggle()
{
    State initial("initial", {});
    State wait("wait", {});

    int event_id = 1;
    auto t = Transition(&initial, &wait, event_id);
    auto tt = TimedTransition(&wait, &initial, 100);

    SimpleFSM fsm(&initial);
    fsm.add(&t, 1);
    fsm.add(&tt, 1);

    auto start = millis();
    auto end = millis();
    unsigned long maxWait = 1000;

    for (int i = 0; i < 3; i++)
    {
        delay(200 * i - (end - start));
        fsm.trigger(event_id);
        while (&initial != fsm.getState() && maxWait > end - start)
        {
            fsm.run(0);
        }
        end = millis();
        TEST_ASSERT_INT32_WITHIN(2, 100 + 200 * i, end - start);
    }
}

void setup()
{
    UNITY_BEGIN();
    RUN_TEST(test_mixed_transition_toggle);
    UNITY_END();
}
void loop() {}
```
The test is running green. I am using https://github.com/bloodhoundmichael/SimpleFSM/commit/0e000e845ea3ae9b2451f41c809d8896a76d0d44. Can you provide a test that is failing?
